// <auto-generated />
namespace OracleEFAttributesTest.Migrations.OracleMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class annotateTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(annotateTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201904220159089_annotateTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
